
-- Create a table for admin settings
CREATE TABLE public.admin_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key TEXT NOT NULL UNIQUE,
  setting_value TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Function to update 'updated_at' column
CREATE OR REPLACE FUNCTION public.update_admin_settings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update 'updated_at' on row update
CREATE TRIGGER on_admin_settings_update
  BEFORE UPDATE ON public.admin_settings
  FOR EACH ROW
  EXECUTE PROCEDURE public.update_admin_settings_updated_at();

-- Insert the default admin password. The previous one was 'vivelesmaries'.
INSERT INTO public.admin_settings (setting_key, setting_value)
VALUES ('admin_password', 'vivelesmaries')
ON CONFLICT (setting_key) DO NOTHING;
