// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sceapjnljmuuvgugqrsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjZWFwam5sam11dXZndWdxcnNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTU0NDcsImV4cCI6MjA2NDczMTQ0N30.ohWSgG50BGqemyUTC_fCjOfu6Shexr6dAbSdB5lt1G4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);