// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duygungzpjvbatjkranv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1eWd1bmd6cGp2YmF0amtyYW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTk5MzQsImV4cCI6MjA2NTk3NTkzNH0.MqGSOwWCRTQj9ekmEaQYYVdB6wF_yQ-u5adpVQzac_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);